"""Add Payment Model and PaymentItem Model

Revision ID: 1599d27936d3
Revises: 7f00834ba739
Create Date: 2025-12-10 15:10:14.927875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1599d27936d3"
down_revision: Union[str, None] = "7f00834ba739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
