"""PaymentModel and PaymentItemModel

Revision ID: 2931f2465c0f
Revises: 48a7a642a582
Create Date: 2025-12-02 17:22:15.045545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2931f2465c0f'
down_revision: Union[str, None] = '48a7a642a582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
