"""Change nullable for cost in Movie Model

Revision ID: 6209f90ef650
Revises: f80ab5675035
Create Date: 2025-12-13 10:17:44.413036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6209f90ef650'
down_revision: Union[str, None] = 'f80ab5675035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'current_price',
                   existing_type=sa.NUMERIC(precision=10, scale=2),
                   nullable=True)

    op.execute('UPDATE movies SET current_price = 0')

    op.alter_column('movies', 'current_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'current_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
