"""Create Order and OrderItem tables

Revision ID: 7bb0b50c615f
Revises: 844c425609d8
Create Date: 2025-11-30 17:56:51.391397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb0b50c615f'
down_revision: Union[str, None] = '844c425609d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'is_active')
    # ### end Alembic commands ###
