"""Add all missing tables

Revision ID: 84251c533e27
Revises: e9a47c0be35b
Create Date: 2025-12-30 17:25:42.072365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84251c533e27'
down_revision: Union[str, None] = 'e9a47c0be35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'current_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'current_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               nullable=False)
    # ### end Alembic commands ###
