"""Add relationship to UserModel for Cart

Revision ID: b6678ecef7b6
Revises: 438100a5d72f
Create Date: 2025-11-26 16:10:55.492225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6678ecef7b6'
down_revision: Union[str, None] = '438100a5d72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
