"""Add Order and PaymentItem Models

Revision ID: f80ab5675035
Revises: 8730a0c0d2e1
Create Date: 2025-12-13 09:57:48.642332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80ab5675035'
down_revision: Union[str, None] = '8730a0c0d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
